### ISSUE TITLE
Week 1 Grades

### ISSUE THREAD

**Issue by jenniferyaya** [jenniferyaya/simple-chat-app#1]
@ericadamski
@xuke918
@anthonyaubrey

**Comment by ericadamski** [comment]
Could you add me as a collaborator so I can close issues once I have given you the marks for them? THanks!

**Comment by jenniferyaya** [comment]
@ericadamski  I did I think? Here is the link: https://github.com/jenniferyaya/simple-chat-app/invitations

**Comment by ericadamski** [comment]
Thank you!
